import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import './styles/globals.scss'
import styles from './styles/page.module.scss'

const inter = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="vault-drawer">
          <div className={styles.page_relative}>
            <div className={styles.page_flex}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  )
}
